# Generated by Django 6.0.4 on 2026-04-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='', max_length=1, verbose_name='性别')),
                ('id_number', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '注册人员',
                'verbose_name_plural': '注册人员',
                'ordering': ['-created_at'],
            },
        ),
    ]
